# 识别行为模式的模板
classify_action_prompt_front: |
  #### 定位
  - 智能助手名称 ：行为模式分类专家
  - 主要任务 ：对输入命令进行行为模式自动分类，识别其所属的行为模式。
  #### 能力
  - 文本分析 ：能够准确分析文本的内容和结构。
  - 分类识别 ：根据分析结果，将文本分类到预定义的种类中。
  #### 知识储备
  - 行为模式种类 ：
    - 1：在某地(具体位置)部署某物
    - 2：从某地部署某物执行某行为目标是某地
    - 3：在某区域(模糊描述)部署某物
    - 4: 某地某物移动到某地
  #### 使用说明
  - 输入 ：一段文本表示一段命令。
  - 输出 ：只输出命令文本所属的种类，即序号1、2、3...，不需要额外解释。 

classify_action_prompt_back: |
  #### 示例
  - 输入1："在 (116.391N, 40.042E) 处部署25人的军队，配有2辆坦克"
    输出1：1
  - 输入2："在(16.391N, -140.042E) 部署4架爱国者导弹发射车，隐蔽待命，打击目标为(150.391N, 60.042E)，每辆发射车配有4枚爱国者导弹"
    输出2：2
  - 输入3："在四川和北京交界处部署3辆坦克"
    输出3：3
  - 输入4："把(116N, 40E)处军队部署到(116N, 60E)处"
    输出4：4


get_info_templates:
  - get_info_template: |
      用户将提供一段文本，提取其中关于结构的信息，并以JSON格式输出。
      EXAMPLE INPUT : 
      在 (116.391N, 40.042E) 处部署25人的军队，配有2辆坦克
      EXAMPLE JSON OUTPUT :
      {
          "action_type": "1",
          "objects": [
              { 
                  "object_type": "坦克",
                  "number": "2",
                  "longitude" : "116.391",
                  "latitude" : "40.042",
              },
              { 
                  "object_type": "军队",
                  "number": "25",
                  "longitude" : "116.391",
                  "latitude" : "40.042",
              }
          ]
      }

  - get_info_template: |
      用户将提供一段文本，提取其中关于结构的信息，并以JSON格式输出。
      EXAMPLE INPUT : 
      在(16.391N, -140.042E) 部署4架爱国者导弹发射车，隐蔽待命，打击目标为(150.391N, 60.042E)，每辆发射车配有4枚爱国者导弹
  
      EXAMPLE JSON OUTPUT :
      {
          "action_type": "2",
          "objects": [
              { 
                  "object_type": "爱国者导弹发射车",
                  "number": "4",
                  "longitude": "16.391",
                  "latitude": "-140.042",
                  "action": "隐蔽待命"
                  "target": {
                      "nickname": "null",
                      "longitude" : "150.391",
                      "latitude" : "60.042",
                  }
                  "object_asset":[
                      {
                          "object_type": "爱国者导弹",
                          "number": "4",
                      }
                  ]
              },
          ]
      }

  - get_info_template: |
      用户将提供一段文本，提取其中关于结构的信息，并以JSON格式输出。
      EXAMPLE INPUT : 
      在四川和北京交界处部署3辆坦克

      EXAMPLE JSON OUTPUT :
      {
          "action_type": "3",
          "objects": [
              { 
                  "object_type": "坦克",
                  "number": "3",
                  "area": "四川和北京交界处"
              },
          ]
      }
  - get_info_template: |
      用户将提供一段文本，提取其中关于结构的信息，并以JSON格式输出。
      EXAMPLE INPUT : 
      把(116N, 40E)处军队部署到(116N, 60E)处

      EXAMPLE JSON OUTPUT :
      {
          "action_type": "4",
          "objects": [
              { 
                  "object_type": "军队",
                  "old_longitude": "116",
                  "old_latitude": "40",
                  "longitude": "116",
                  "latitude": "60"
              },
          ]
      }

find_op_action_list: [4,]
      
json2xml_background: |
  整个坐标屏幕大小为2000x2000，用户以中心x=1000，y=1000为中心，左上角为坐标原点,x轴向下为正方向，y轴向右为正方向，进行描述，
      longitude表示经度，latitude表示纬度，action表示动作，target表示目标，object_type表示对象类型，object_asset表示对象资产，
      longitude即x轴坐标，latitude即y轴坐标
      遵从上北下南左西右东的原则，例如东南即x>1000，y>1000，西北即x<1000，y<1000,东北即x>1000，y<1000，西南即x<1000，y>1000。
      tank的大小为200*200, soldier的大小为100*100, missile-launcher的大小为150*150.


json2xml_prompt: |
  用户将输入一个json对象，将其转换为xml格式:
  背景信息如下：{ json2xml_background }

  EXAMPLE JSON INPUT: 
  {
      "action_type": 2,
      "objects": [
          {
              "object_type": "missile-launcher",
              "number": 4,
              "longitude": 1081.955,
              "latitude": 299.78999999999996,
              "action": "隐蔽待命",
              "target": {
                  "nickname": "无",
                  "longitude": 1751.955,
                  "latitude": 1300.21
              },
              "object_asset": [
                  {
                      "object_type": "missile",
                      "number": 4
                  }
              ]
          }
      ]
  }

  EXAMPLE XML OUTPUT:
  <g>
  <rect fill="url(#missile-launcher_p)" height="150" width="150" x="1081" y="299">
      <title>
          详细信息：
          数量：4
          动作：隐蔽待命
          目标：
          目标位置：1751.955，1300.21
          武器配置：
          武器类型：missile
          数量：4
      </title>
  </rect>
  <use href="#aim" x="1751" y="1300"></use>
  <line stroke="red" stroke-dasharray="5,5" stroke-width="2" x1="1081" x2="1751" y1="299" y2="1300"></line>
  </g>